# Olympic Event Analysis

In [ ]:
import pandas as pd
import numpy as np
import dash 
import dash_core_components as dcc
import dash_html_components as html
import plotly.graph_objs as go
from dash.dependencies import Input, Output, State


ds = pd.read_csv('results.csv', error_bad_lines=False)

# Clean 'None' values in results    
df = ds[ds.Result != None]

# Clean h labels in results
for i in range(0,len(df),1):
    if 'h' in df['Result'][i]:
        df['Result'][i] = df['Result'][i].replace('h', ':')

# Clean - labels in results
for i in range(0,len(df),1):
    if '-' in df['Result'][i]:
        df['Result'][i] = df['Result'][i].replace('-', ':')
        
df = df.sort_values('Result')

grey = '#283849'
blue = '#BEE2F0'

app = dash.Dash()

app.layout = html.Div([
    html.Div([
        html.H1('Olympic Analysis')
    ], style = {'width':'100%', 
                'textAlign':'center',
                'vertical-align': 'middle',
                'font-family':'helvetica',
                'color':'{}'.format(blue)}),
    html.Div([
        html.H2('Event'),
        dcc.Dropdown(
            id = 'event-dropdown',
            options=[{'label': event, 'value': event} for event in ds['Event'].unique()
                    ])
    
    ], style={'color':grey,'width': '20%','align':'centre','font-family':'helvetica',
              'textAlign':'center'}),
    html.Div([
        dcc.Graph(id='ScatGraph-output')
    ],style={'width': '50%',
                 'font-family':'helvetica',
                 'font':{'color':'{}'.format(blue)},
                 'display':'inline-block'}),
    html.Div([
        dcc.Graph(id='PieGraph-output')
    ],style={'width': '50%',
                 'font-family':'helvetica',
                 'font':{'color':'{}'.format(blue)},
                 'display':'inline-block'})
        ],
style = {'background-color':'{}'.format(grey)})

@app.callback(Output('ScatGraph-output', 'figure'),
             [Input('event-dropdown', 'value')])
def updategraph(event):
    dss = df[df['Event'] == event]
    traces = []
    for eventname in dss['Event'].unique():
        ds_by_event = dss[dss['Event'] == eventname]
        traces.append(go.Scatter(
        x = ds_by_event['Year'],
        y = ds_by_event['Result'],
        mode = 'markers',
        marker = {'size': 12,
                'color': 'rgb(51,204,153)',
                'line': {'width': 2}},
        text = ds_by_event['Event'],
        name = eventname
        ))
        
    return{
        'data':traces,
        'layout': go.Layout(
        xaxis={'type':'linear', 'title': 'Year'},
        yaxis={'title':'Result'},
        plot_bgcolor=grey,
        paper_bgcolor=grey,
        title = 'Performance over time',
        font = {'color':'{}'.format(blue)})
    }
     
@app.callback(Output('PieGraph-output', 'figure'),
             [Input('event-dropdown', 'value')])
def updategraph(event):
    dss = df[df['Event'] == event]
    traces = []
    for eventname in dss['Event'].unique():
        ds_by_event = dss[dss['Event'] == eventname]
        dff = ds_by_event['Nationality'].value_counts().rename_axis('Nation').reset_index(name='Counts')  
        traces.append(go.Pie(
        labels = dff['Nation'],
        values = dff['Counts'],
        name = eventname
        ))
        
    return{
        'data':traces,
        'layout': go.Layout(
        plot_bgcolor=grey,
        paper_bgcolor=grey,
        title = 'Medals per Nation',
        font = {'color':'{}'.format(blue)})
    }

    
    
if __name__ == '__main__':
    app.run_server()

b'Skipping line 156: expected 8 fields, saw 9\nSkipping line 157: expected 8 fields, saw 9\nSkipping line 158: expected 8 fields, saw 9\nSkipping line 317: expected 8 fields, saw 9\nSkipping line 318: expected 8 fields, saw 9\nSkipping line 319: expected 8 fields, saw 9\nSkipping line 1658: expected 8 fields, saw 9\nSkipping line 1659: expected 8 fields, saw 9\nSkipping line 1660: expected 8 fields, saw 9\nSkipping line 1784: expected 8 fields, saw 9\nSkipping line 1785: expected 8 fields, saw 9\nSkipping line 1786: expected 8 fields, saw 9\n'
/Users/daniel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:18: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

 * Serving Flask app "__main__" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off

/Users/daniel/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:23: SettingWithCopyWarning:


A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

 * Running on http://127.0.0.1:8050/ (Press CTRL+C to quit)
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_renderer/react@16.8.6.min.js?v=1.0.0&m=1561062262 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_renderer/react-dom@16.8.6.min.js?v=1.0.0&m=1561062262 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_renderer/prop-types@15.7.2.min.js?v=1.0.0&m=1561062262 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_html_components/dash_html_components.min.js?v=1.0.0&m=1561063963 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_core_components/highlight.pack.js?v=1.0.0&m=1563307603 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_renderer/dash_renderer.min.js?v=1.0.0&m=1561062262 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_core_components/dash_core_components.min.js?v=1.0.0&m=1563307603 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:44] "GET /_dash-component-suites/dash_core_components/plotly-1.48.3.min.js?v=1.0.0&m=1563307603 HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:45] "GET /_dash-layout HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:45] "GET /_dash-dependencies HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:45] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:51] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:51] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:58] "POST /_dash-update-component HTTP/1.1" 200 -
127.0.0.1 - - [21/Aug/2019 17:08:58] "POST /_dash-update-component HTTP/1.1" 200 -

b'Skipping line 156: expected 8 fields, saw 9\nSkipping line 157: expected 8 fields, saw 9\nSkipping line 158: expected 8 fields, saw 9\nSkipping line 317: expected 8 fields, saw 9\nSkipping line 318: expected 8 fields, saw 9\nSkipping line 319: expected 8 fields, saw 9\nSkipping line 1658: expected 8 fields, saw 9\nSkipping line 1659: expected 8 fields, saw 9\nSkipping line 1660: expected 8 fields, saw 9\nSkipping line 1784: expected 8 fields, saw 9\nSkipping line 1785: expected 8 fields, saw 9\nSkipping line 1786: expected 8 fields, saw 9\n'

,Gender,Event,Location,Year,Medal,Name,Nationality,Result
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77

In [6]:
import numpy as np 
import pandas as pd
import statistics

ds = pd.read_csv('results.csv', error_bad_lines=False)
ds.head()

ds = ds[ds.Result != None]




    
    


##dss = ds[ds['Event'] == '100M Men']
#dss

#natcount = dss['Nationality'].value_counts()


#df = natcount.rename_axis('Nation').reset_index(name='Counts')
##df

b'Skipping line 156: expected 8 fields, saw 9\nSkipping line 157: expected 8 fields, saw 9\nSkipping line 158: expected 8 fields, saw 9\nSkipping line 317: expected 8 fields, saw 9\nSkipping line 318: expected 8 fields, saw 9\nSkipping line 319: expected 8 fields, saw 9\nSkipping line 1658: expected 8 fields, saw 9\nSkipping line 1659: expected 8 fields, saw 9\nSkipping line 1660: expected 8 fields, saw 9\nSkipping line 1784: expected 8 fields, saw 9\nSkipping line 1785: expected 8 fields, saw 9\nSkipping line 1786: expected 8 fields, saw 9\n'

In [5]:
ds

,Gender,Event,Location,Year,Medal,Name,Nationality,Result
0,M,10000M Men,Rio,2016,G,Mohamed FARAH,USA,25:05.17
1,M,10000M Men,Rio,2016,S,Paul Kipngetich TANUI,KEN,27:05.64
2,M,10000M Men,Rio,2016,B,Tamirat TOLA,ETH,27:06.26
3,M,10000M Men,Beijing,2008,G,Kenenisa BEKELE,ETH,27:01.17
4,M,10000M Men,Beijing,2008,S,Sileshi SIHINE,ETH,27:02.77
5,M,10000M Men,Beijing,2008,B,Micah KOGO,KEN,27:04.11
6,M,10000M Men,Sydney,2000,G,Haile GEBRSELASSIE,ETH,27:18.20
7,M,10000M Men,Sydney,2000,S,Paul TERGAT,KEN,27:18.29
8,M,10000M Men,Sydney,2000,B,Assefa MEZGEBU,ETH,27:19.75
9,M,10000M Men,Barcelona,1992,G,Khalid SKAH,MAR,27:46.70
10,M,10000M Men,Barcelona,1992,S,Richard CHELIMO,KEN,27:47.72
11,M,10000M Men,Barcelona,1992,B,Addis ABEBE,ETH,28:00.07
12,M,10000M Men,Los Angeles,1984,G,Alberto COVA,ITA,27:47.54
13,M,10000M Men,Los Angeles,1984,S,Michael MCLEOD,GBR,28:06.22
14,M,10000M Men,Los Angeles,1984,B,Michael MUSYOKI,KEN,28:06.46
15,M,10000M Men,Montreal,1976,G,Lasse VIREN,FIN,27:40.38
16,M,10000M Men,Montreal,1976,S,Carlos LOPES,POR,27:45.17
17,M,10000M Men,Montreal,1976,B,Brendan FOSTER,GBR,27:54.92
18,M,10000M Men,Mexico,1968,G,Naftali TEMU,KEN,29:27.4
19,M,10000M Men,Mexico,1968,S,Mamo WOLDE,ETH,29:28.0
20,M,10000M Men,Mexico,1968,B,Mohamed GAMMOUDI,TUN,29:34.2
21,M,10000M Men,Rome,1960,G,Pyotr BOLOTNIKOV,URS,28:32.2
22,M,10000M Men,Rome,1960,S,Hans GRODOTZKI,EUA,28:37.0
23,M,10000M Men,Rome,1960,B,David POWER,AUS,28:38.2
24,M,10000M Men,Helsinki,1952,G,Emil ZÃTOPEK,TCH,29:17.0
25,M,10000M Men,Helsinki,1952,S,Alain MIMOUN,FRA,29:32.8
26,M,10000M Men,Helsinki,1952,B,Aleksandr ANUFRIYEV,URS,29:48.2
27,M,10000M Men,Berlin,1936,G,Ilmari SALMINEN,FIN,30:15.4
28,M,10000M Men,Berlin,1936,S,Arvo ASKOLA,FIN,30:15.6
29,M,10000M Men,Berlin,1936,B,Volmari ISO-HOLLO,FIN,30:20.2
...,...,...,...,...,...,...,...,...
2352,W,Shot Put Women,Athens,2004,G,Yumileidi CUMBA,CUB,19.59
2353,W,Shot Put Women,Athens,2004,S,Nadine KLEINERT-SCHMITT,GER,19.55
2354,W,Shot Put Women,Atlanta,1996,G,Astrid KUMBERNUSS,GER,20.56
2355,W,Shot Put Women,Atlanta,1996,S,Xinmei SUI,CHN,19.88
2356,W,Shot Put Women,Atlanta,1996,B,Irina KHUDOROZHKINA,RUS,19.35
2357,W,Shot Put Women,Moscow,1980,G,Ilona SCHOKNECHT-SLUPIANEK,GDR,22.41
2358,W,Shot Put Women,Moscow,1980,S,Esfira DOLCHENKO-KRACHEVSKAYA,URS,21.42
2359,W,Shot Put Women,Moscow,1980,B,Margitta DROESE-PUFE,GDR,21.2
2360,W,Shot Put Women,Munich,1972,G,Nadezhda CHIZHOVA,URS,21.03
2361,W,Shot Put Women,Munich,1972,S,Margitta HELMBOLD-GUMMEL,GDR,20.22
2362,W,Shot Put Women,Munich,1972,B,Ivanka KHRISTOVA,BUL,19.35
2363,W,Shot Put Women,Tokyo,1964,G,Tamara PRESS,URS,18.14
2364,W,Shot Put Women,Tokyo,1964,S,Renate GARISCH-CULMBERGER-BOY,EUA,17.61
2365,W,Shot Put Women,Tokyo,1964,B,Galina ZYBINA,URS,17.45
2366,W,Triple Jump Women,Rio,2016,G,Caterine IBARGUEN,COL,15.17
2367,W,Triple Jump Women,Rio,2016,S,Yulimar ROJAS,VEN,14.98
2368,W,Triple Jump Women,Rio,2016,B,Olga RYPAKOVA,KAZ,14.74
2369,W,Triple Jump Women,Beijing,2008,G,Francoise MBANGO ETONE,CMR,15.39
2370,W,Triple Jump Women,Sydney,2000,G,Tereza MARINOVA,BUL,15.2
2371,W,Triple Jump Women,Sydney,2000,S,Tatyana LEBEDEVA,RUS,15.0
2372,W,Triple Jump Women,Sydney,2000,B,Olena HOVOROVA,UKR,14.96
2373,W,Triple Jump Women,London,2012,G,Olga RYPAKOVA,KAZ,14.98
2374,W,Triple Jump Women,London,2012,S,Caterine IBARGUEN,COL,14.8
2375,W,Triple Jump Women,London,2012,B,Olga SALADUKHA,UKR,14.79
2376,W,Triple Jump Women,Athens,2004,G,Francoise MBANGO ETONE,CMR,15.3
2377,W,Triple Jump Women,Athens,2004,S,Hrysopiyi DEVETZI,GRE,15.25
2378,W,Triple Jump Women,Athens,2004,B,Tatyana LEBEDEVA,RUS,15.14
2379,W,Triple Jump Women,Atlanta,1996,G,Inessa KRAVETS,UKR,15.33
2380,W,Triple Jump Women,Atlanta,1996,S,Inna LASOVSKAYA,RUS,14.98
2381,W,Triple Jump Women,Atlanta,1996,B,Sarka KASPARKOVA,CZE,14.98

[]

In [ ]:
@app.callback(Output('PieGraph-output', 'figure'),
             [Input('event-dropdown','value')])
def updatePie(event):
    dss = ds[ds['Event'] == event]
    traces = []
    for natUnique in dss['Event'].unique():
        ds_by_nationality = dss[dss['Event'] == natUnique]
        traces.append(go.Pie(
        labels = ds_by_nationality['Nationality'],
        values = np.count(ds_by_nationality['Nationality']),
        name = natUnique
        ))
        
        
    return{
        'data':traces,
        'layout': go.Layout(title=f"Medals per Nation", margin={"l": 300, "r": 300, },
                            legend={"x": 1, "y": 0.7})}